name: soulbook
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^0.1.0
  bloc: ^0.9.5
  flutter_bloc: 0.6.0
  meta: ^1.1.6
  equatable: ^0.1.6
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  intro_slider: ^1.1.4
  uuid: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0
  build_runner: ^0.10.1
  kiwi_generator: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/intro0.png
    - assets/intro1.png
    - assets/intro2.png
    - assets/block1.png
    - assets/block2.png
    - assets/block3.png
    - assets/block4.png
    - assets/block5.png
