name: core
description: Common shared code for Soulbook app
version: 0.0.1
author: dmba <dmytro.babiienko@gmail.com>
homepage: https://github.com/dmba/soulbook

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  kiwi: ^0.1.0

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  build_runner: ^0.10.1
  kiwi_generator: ^0.1.1
  bloc: ^0.8.3
