name: core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.1
  kiwi_generator: ^0.1.1
  bloc: ^0.8.3

flutter:
  uses-material-design: true
